image: mcr.microsoft.com/dotnet/core/sdk:3.1

stages:
    - build
    - test
    - deploy

before_script:
    - "dotnet restore"

build_job:
    stage: build
    script:
        - "dotnet build"

test_job:
    stage: test
    script:
        - "dotnet test"

deploy_job: 
    stage: deploy
    variables:
        deploy_path: "src/App/"
    artifacts:
        paths:
            - src/App/bin/release
        expire_in: 1 week
    script:
    # cd to where csproj is
    - cd $deploy_path
    # publish the files - this will generate the publish files in bin/release 
    - dotnet publish -c release