image: mcr.microsoft.com/dotnet/core/sdk:3.1

stages:
    - build

variables:
    test: "Example.Test"

before_script:
    - "dotnet restore"

build:
    stage: build
    script:
        - "dotnet build"